package com.bofa.entity;

import com.ai.nbs.common.spring.dao.entity.MybatisEntity;
import com.bofa.attribute.MessageType;
import lombok.Data;

import java.io.Serializable;

/**
 * @author Bofa
 * @version 1.0
 * @decription com.bofa.entity
 * @date 2019/4/13
 */
@Data
public class UserMessage extends MybatisEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.MESSAGEID
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private String messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.FROMUSERNAME
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private String fromusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.TOUSERNAME
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private String tousername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.TOUSERID
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private Integer touserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.FROMUSERID
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private Integer fromuserid;

    /**
     * Database Column Remarks:
     * 信息类型
     * 1:文字
     * 2:图片
     * 3:视频
     * 4:语音
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.MESSAGETYPE
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private Integer messagetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.DATETIME
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private String datetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_MESSAGE.CONTENT
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_MESSAGE
     *
     * @mbg.generated 2019-04-20 22:27:06
     */
    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        return "[MESSAGE] " + datetime + "\n" +
                "(" + fromusername + ") -> \"" +
                content + "\"";
    }
}
