package com.bofa.entity;

import com.ai.nbs.common.spring.dao.entity.MybatisEntity;
import com.bofa.attribute.NoticeType;
import lombok.Data;

import java.io.Serializable;

/**
 * Database Table Remarks:
 * 客户端通知缓存
 * <p>
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table USER_NOTICE
 *
 * @mbg.generated do_not_delete_during_merge 2019-04-19 23:05:56
 */
@Data
public class UserNotice extends MybatisEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.ID
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.USERID
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.USERNAME
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.NOTICEID
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private Integer noticeid;

    /**
     * Database Column Remarks:
     * 如果是好友离线信息或者好友验证信息
     * 则为好友用户名
     * 如果是异地通知则为System
     * 群聊信息则为群聊房间名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.NOTICENAME
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private String noticename;

    /**
     * Database Column Remarks:
     * 1: 已读
     * 2: 未读
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.NOTICESTATUS
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private Integer noticestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.NOTICEDATETIME
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private String noticedatetime;

    /**
     * Database Column Remarks:
     * 1:好友离线信息
     * 2:好友验证信息
     * 3:异地登录信息
     * 4:群聊信息
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.NOTICETYPE
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private Integer noticetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_NOTICE.NOTICECONTENT
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private String noticecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_NOTICE
     *
     * @mbg.generated 2019-04-19 23:05:56
     */
    private static final long serialVersionUID = 1L;

    @Override
    public String toString() {
        return "\n" + "[NOTICE] " +
                "#" + NoticeType.findByType(noticetype) + "\n" +
                "[" + noticedatetime + "]" + " " +
                "<" + noticename + ">" + "\n" +
                " - " + noticecontent;
    }
}