-- auto-generated definition
CREATE TABLE USER_FRIENDS
(
  ID             INTEGER      PRIMARY KEY AUTO_INCREMENT,
  USERID         INTEGER      NOT NULL,
  USERFRIENDID   INTEGER      NOT NULL,
  USERFRIENDNAME VARCHAR(256) NOT NULL,
  LASTCHATTIME   TIMESTAMP,
  REMARK         VARCHAR(256)
);

COMMENT ON TABLE USER_FRIENDS
IS '上一次登录的用户的好友信息(只存储单用户)';

COMMENT ON COLUMN USER_FRIENDS.LASTCHATTIME
IS '上一次聊天时间';

COMMENT ON COLUMN USER_FRIENDS.REMARK
IS '用户备注';


