-- auto-generated definition
CREATE TABLE USER_FRIENDS
(
  ID             INTEGER default (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_9CE0580A_5F7D_4DF3_AC6A_0A7851E6A9FB),
  USERID         INTEGER      not null,
  USERFRIENDID   INTEGER      not null,
  USERFRIENDNAME VARCHAR(256) not null,
  LASTCHATTIME   TIMESTAMP,
  REMARK         VARCHAR(256)
);

COMMENT ON TABLE USER_FRIENDS
IS '上一次登录的用户的好友信息(只存储单用户)';

COMMENT ON COLUMN USER_FRIENDS.LASTCHATTIME
IS '上一次聊天时间';

COMMENT ON COLUMN USER_FRIENDS.REMARK
IS '用户备注';


